import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import "next-auth";
import { FaSpotify } from "react-icons/fa";
import { HiLightBulb, HiSparkles } from "react-icons/hi";
import { motion } from "framer-motion";
import Image from "next/image";
import {
  HiViewGridAdd,
  HiOutlineClock,
  HiOutlineHeart,
  HiOutlineChat,
  HiOutlineCollection,
  HiOutlineCursorClick,
} from "react-icons/hi";

export default function Home() {
  const { data: session, status } = useSession();
  return (
    <>
      <Head>
        <title>Listemotions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative flex min-h-screen  flex-col items-center justify-center ">
        <div className="absolute -top-[700px] left-[160px] z-10 h-[1000px] w-[1000px] rounded-full bg-[#FF0000] p-4 opacity-20 blur-[90px]"></div>
        <main className="z-50 flex h-screen w-[900px] flex-col items-center justify-center  gap-6">
          <h2 className="text-4xl font-bold text-[#FF0000]">Listemotions</h2>
          <div className=" flex flex-col items-center justify-center gap-2">
            {" "}
            <motion.h1
              initial={{ opacity: 0, y: -50 }}
              animate={{ opacity: 2, y: 0 }}
              transition={{ duration: 1 }}
              className="font-bold"
            >
              Perfect Playlists, Elevate Your Listening Experience
            </motion.h1>
            <p className="flex items-center gap-1 font-medium text-gray-300">
              <span>Make playlists for</span>
              <FaSpotify color="white" />
              <span className="font-bold text-white">Spotify</span>{" "}
              <span>powered by</span>
              <span className="flex items-center text-white">
                {" "}
                <HiSparkles />
                <span className="font-bold"> AI</span>
              </span>
            </p>
          </div>

          {status === "unauthenticated" ? (
            <motion.button
              whileTap={{ scale: 0.9 }}
              whileHover={{ scale: 1.1 }}
              className="flex items-center justify-center gap-2 rounded-2xl bg-[#FF0000] px-5 py-3 text-[14px] font-medium shadow-lg"
              onClick={() => signIn("spotify", { callbackUrl: "/playlists" })}
            >
              Log in with Spotify <FaSpotify size={17} />
            </motion.button>
          ) : (
            <div>
              <button onClick={() => signOut()}>Log out</button>
            </div>
          )}
        </main>
        <section className=" h-screen  w-full p-10 ">
          <div className=" flex flex-col items-center justify-center rounded-xl bg-[#050505] p-5 ring-1 ring-gray-900 ">
            <h2 className="font-semibold">
              Writing prompts & personalized playlist ideas
            </h2>
            <p className="text-[14px] font-medium text-gray-300">
              Break through writer's block with great ideas and suggestions.
            </p>
            <div className="grid w-full grid-cols-3">
              <div className="flex flex-col items-center justify-center gap-4 pl-5 pr-20">
                <motion.div
                  initial={{ opacity: 0, y: -50 }}
                  animate={{ opacity: 2, y: 0 }}
                  transition={{ duration: 1 }}
                >
                  <div className="flex items-center gap-1 gap-2">
                    <HiOutlineChat size={18} />
                    <h4 className="font-semibold">Never run out of ideas</h4>
                  </div>
                  <p className="text-[14px] text-gray-400">
                    Enjoy daily prompts and ideas to inspire your writing.
                  </p>
                </motion.div>

                <motion.div
                  initial={{ opacity: 0, y: -50 }}
                  animate={{ opacity: 2, y: 0 }}
                  transition={{ duration: 1 }}
                >
                  <div className="flex items-center gap-1 gap-2">
                    <HiOutlineCollection size={18} />
                    <h4 className="font-semibold">
                      Use AI for personalized suggestions
                    </h4>
                  </div>
                  <p className="text-[14px] text-gray-400">
                    Get inspiration from ideas based on your own past tweets.
                  </p>
                </motion.div>

                <motion.div
                  initial={{ opacity: 0, y: -50 }}
                  animate={{ opacity: 2, y: 0 }}
                  transition={{ duration: 1 }}
                >
                  <div className="flex items-center gap-1 gap-2">
                    <HiOutlineCursorClick size={18} />
                    <h4 className="font-semibold">Flick through topics</h4>
                  </div>
                  <p className="text-[14px] text-gray-400">
                    Or skim through curated collections of trending tweets for
                    each topic.
                  </p>
                </motion.div>
              </div>
              <div className="relative col-span-2 flex h-[510px] items-center justify-center">
                <img src="/promptImage.png" className="z-50 " alt="example" />
                <div className="absolute  z-10 h-[155px] w-[242px] rounded-full bg-[#C30000]  blur-[200px]"></div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
