import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import axios from 'axios'
import 'next-auth'
import { FaSpotify } from "react-icons/fa";


export default function Home() {

  const { data: session, status } = useSession();

  const playlistId = "5lga9js0jSBNM9TFv7UF18";

  const createPlaylist = async () => {
    if (session) {
      const playlistData = {
        "name": "REGGETON🫁",
        "description": "Testing",
        "public": false
      }

      const headers = {
        Authorization: `Bearer ${session.accessToken}`
      }
      try {
        const response = await axios.post(`https://api.spotify.com/v1/users/${session.user.id}/playlists`, playlistData, {
          headers
        });
        console.log(response.data)
      } catch (error) {
        console.log(error)
      }
    }
  }



  return (
    <>
      <Head>
        <title>Listemotions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='relative w-full h-screen -mt-20 flex justify-center items-center flex-col'>
        <div className='absolute bg-[#FF0000] p-4 rounded-full w-[1000px] h-[1000px] blur-[90px] opacity-20 -left-[200px]'></div>
        {/* <div className='absolute bg-[#0065FF] p-4 rounded-full w-[100px] h-[100px] blur-[70px] opacity-100 left-[530px] top-45'></div> */}
        <div className='grid grid-cols-2 px-5 z-50'>
          <div className='flex flex-col justify-start gap-4 '>
            <h2 className='font-black text-4xl text-[#FF0000]'>Listemotions</h2>
            <h1>
              Stop hearing the same thing. <br />
              Create emotions in Spotify playlists with AI.
            </h1>
            {
              status === "unauthenticated" ? (
                <div>
                  <button className='flex justify-center items-center gap-2 bg-[#FF0000] text-[14px] font-medium px-5 py-3 rounded-xl shadow-lg' onClick={() => signIn("spotify", { callbackUrl: "/generate" })}>Sign with Spotify <FaSpotify size={17} /></button>
                </div>
              ) : (
                <div>
                  <button onClick={() => signOut()}>Log out</button>
                  <button onClick={() => createPlaylist()}>Create a playlist</button>
                </div>
              )
            }
          </div>
        </div>
      </div>
    </>
  )
}
